version: '3'

services:
  earthquake-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: earthquake-bot:latest
    restart: always
    volumes:
      - subscriber-data:/app/data
      - ./earthquake-notifier/.env:/app/.env
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  subscriber-data:
