services:
  earthquake-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: earthquake-bot:latest
    restart: always
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - subscriber-data:/app/data
      - log-data:/app/logs
      - ./earthquake-notifier/.env:/app/.env:ro
      - /tmp
    environment:
      - NODE_ENV=production
      - LOG_DIR=/app/logs
    ports:
      - "127.0.0.1:8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
    cpu_count: 1
    cpu_percent: 50
    mem_limit: 512m
    mem_reservation: 256m
    pids_limit: 50

volumes:
  subscriber-data:
    driver: local
  log-data:
    driver: local
