name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'earthquake-notifier/package-lock.json'
      
      - name: Install dependencies
        run: cd earthquake-notifier && npm ci
      
      - name: Run linting
        run: cd earthquake-notifier && npm run lint
      
      - name: Build TypeScript
        run: cd earthquake-notifier && npm run build

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-bot:${{ github.sha }} .
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-bot:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy earthquake-bot \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-bot:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 512Mi \
            --min-instances 1
      
      - name: Tag Latest Image
        run: |
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-bot:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-bot:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-bot:latest
